### ISSUE TITLE
Could not download the whole standard output from `Output` tab

### ISSUE THREAD

**Issue by soanduong** [comet-ml/comet-examples#15]
Hi all,

I would like to download the whole standard output from `Output` tab.

For almost experiments, I can download the whole standard output. The downloaded text file always starts with `COMET INFO: Experiment is live on comet.ml https://www.comet.ml/`.

However, for few experiments, I could not download the whole standard output. The downloaded text file contains the output of few steps in training, e.g.
`2405/2890 [=======================>......]- ETA: 5:08 - loss: 0.4637 - sim_loss: 0.4488 - smooth_3d_loss: 0.0204 - anat_loss: -0.4181 - sim_loss_1: 0.44882406/2890 [=======================>......]- ETA: 5:07 - loss: 0.4636 - sim_loss: 0.4488 - smooth_3d_loss: 0.0204 - anat_loss: -0.4181 - sim_loss_1: 0.44882407/2890 [=======================>......]- ETA: 5:06 - loss: 0.4636 - sim_loss: 0.4488 - smooth_3d_loss: 0.0204 - anat_loss: -0.4181 - sim_loss_1: 0.44882408/2890 [=======================>......]- ETA: 5:06 - loss: 0.4636 - sim_loss: 0.4488 - smooth_3d_loss: 0.0204 - anat_loss: -0.4181 - sim_loss_1: 0.44882409/2890 [========================>.....]- ETA: 5:05 - loss: 0.4636 - sim_loss: 0.4487 - smooth_3d_loss: 0.0204 - anat_loss: -0.4181 - sim_loss_1: 0.44872410/2890 [========================>.....]- ETA: 5:04 - loss: 0.4636 - sim_loss: 0.4487 - smooth_3d_loss: 0.0204 - anat_loss: -0.4181 - sim_loss_1: 0.4487
...`

Do you know what the problem is? And how to download the whole standard output for those experiments.

Thank you very much.

**Comment by dsblank** [comment]
Can you send us a link to the experiment at support@comet.ml ? As a workaround, you can:

```python
from comet_ml import APIExperiment

e = APIExperiment(previous_experiment="...")
output = e.get_output()
```

**Comment by soanduong** [comment]
> ```python
> e = APIExperiment(previous_experiment="...")
> ```

Thanks for your reply. I try
```
from comet_ml.api import APIExperiment
e = APIExperiment(api="my_api", workspace="my_workspace", project="my_project", experiment="my_experiment")
```
then I got the error:
```
Traceback (most recent call last):
  File "C:\Users\stmd795\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-47-ecaaa69c876b>", line 1, in <module>
    e = APIExperiment(api="G0ToK2squh8dLSZ25fFe3a7du", workspace="soanduong", project="tmi_exps", experiment="snet_lncc_hcp3Tfmri_1D")
  File "C:\Users\stmd795\AppData\Local\Continuum\anaconda3\lib\site-packages\comet_ml\api.py", line 100, in __init__
    self._api._build_cache(self.workspace, self.project, experiment_key)
AttributeError: 'str' object has no attribute '_build_cache'
```

**Comment by dsblank** [comment]
Here, `api` is an API(), not an `api_key` and `experiment` should be `experiment_name` (I assume, depending on what you are trying to do). So you would:

```
e = APIExperiment(
  api_key="my_api_key", 
  workspace="my_workspace", 
  project="my_project", 
  experiment_name="my_experiment_name")
```
There are more examples here: https://www.comet.ml/docs/python-sdk/Comet-Python-API/

**Comment by soanduong** [comment]
> e = APIExperiment(
>   api_key="my_api_key", 
>   workspace="my_workspace", 
>   project="my_project", 
>   experiment_name="my_experiment_name")

I can get the standard output of the experiment by Python like:
```
from comet_ml import API

# get the name of the workspace
comet_api = API(rest_api_key=my_api)
workspace = comet_api.get()
print(workspace)

# get all the projects
projects = comet_api.get(workspace)
print(projects)

# get the 'my_project' project
exps = comet_api.get(workspace, 'my_project')
print(exps)

# get the stdout of the first experiment of the project
stdout = exps[0].stdout
```

However, I get the same result as downloading from the comet_ml website.

P.S. have you received the link of my experiment through email?

**Comment by dsblank** [comment]
@soanduong Yes, thank you; received!

We are tracking this down...

**Comment by dsblank** [comment]
Followups via email.
