### ISSUE TITLE
Documentation issue: How can I add tensorboard summaries?

### ISSUE THREAD

**Issue by rmminusrslash** [comet-ml/comet-examples#6]
https://www.comet.ml/docs/python-sdk/tensorflow/

simply says 

> If you're already using Tensorboard then Comet works out of the box.

I don't see how declaring an experiment will transfer my summary tensors to the comet api?

**Comment by dsblank** [comment]
Comet does some very clever injection of code into the TensorFlow classes and functions to also get that information reported to Comet. We could clarify that sentence a bit to make that more clear. Does that help?

**Comment by dsblank** [comment]
Also, if you have examples of what type of summary information that Comet doesn't provide but you would like, give us some details (screen shot, text example, link, etc).
