### ISSUE TITLE
requirements.txt out of date

### ISSUE THREAD

**Issue by edu-gp** [comet-ml/comet-examples#7]
Hi folks, when you create a new venv and try `pip install -r requirements.txt`, looks like tensorflow needs to be updated

```
ERROR: Could not find a version that satisfies the requirement tensorflow<1.12.0 (from -r requirements.txt (line 2)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
ERROR: No matching distribution found for tensorflow<1.12.0 (from -r requirements.txt (line 2))
```

**Comment by dsblank** [comment]
Thanks @edu-gp ! Do you know how to make a PR in git? If so, could you make the above change, test it out (please use tensorflow=1.13.x) and submit?

**Comment by edu-gp** [comment]
Yea here you go https://github.com/comet-ml/comet-examples/pull/8

**Comment by dsblank** [comment]
Thanks so much!

**Comment by edu-gp** [comment]
Happy to help!
